Resolver: CudaAllPairsResolver
#Resolver: CudaStaticResolver

NBodyConfig:
    NumParticles: 20000

    ResolverSettings:
        Mtot: 96.9e10
        Msf: 0.14
        Rs: 3160
        Rdm: 6320
        a: 1.5
        Ca: 4.0
        CloudChance: 0.001
        CloudMassCoef: 1000.0


        dT: 0.1
        threadsPerBlock: 256

    ViewerSettings:
        WindowTitle: N-Body Window
        WindowWidth: 1288
        WindowHeight: 728
        MaxFPS: 60
        InitialZoom: 15
        ExportFrames: false
        ExportLocation: d:\Temp\Frames\
        ExportFilePrefix: 99k-Msf0.14-Mtot96.9e10_
        ParticleSize: 1